name: Python application

on:
  push:
      branches: [develop, main]
  pull_request:
    branches: [ develop, main ]
  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest || true
    - name: Test with pytest and create a report
      run: |
        pytest --html=report.html || true

    - name: Lint with flake8 and create a report
      run: |
          flake8 . --format=html --htmldir=flake8_report --exit-zero

    - name: Upload reports
      uses: actions/upload-artifact@v2
      with:
        name: Test and lint reports
        path: |
          report.html
          flake8_report
